# Generated by Django 5.1.3 on 2024-11-28 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва кінотеатру')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна квитка')),
                ('seats_count', models.PositiveIntegerField(verbose_name='Кількість місць')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Кінотеатр',
                'verbose_name_plural': 'Кінотеатри',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва фільму')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('duration', models.PositiveIntegerField(verbose_name='Тривалість (хвилини)')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Фільм',
                'verbose_name_plural': 'Фільми',
            },
        ),
        migrations.CreateModel(
            name='MovieScreenings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата початку показу')),
                ('screening_duration', models.PositiveIntegerField(verbose_name='Тривалість показу (дні)')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='cinema.cinemas', verbose_name='Кінотеатр')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='cinema.movies', verbose_name='Фільм')),
            ],
            options={
                'verbose_name': 'Показ',
                'verbose_name_plural': 'Покази',
            },
        ),
    ]
