# Generated by Django 5.1.3 on 2024-11-27 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_name", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalization",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_name.patients"
            ),
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
